### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by XusBadia** [paullla/bolt-extension-infinite-scroll#2]
I tried loading it from the CMS itself and the extension won't appear. I've also tried the manual install, but Bolt won't recognize it. Is there something I'm missing?

Thanks.

**Comment by GwendolenLynch** [comment]
@XusBadia there isn't a tagged release, so you will need to set `stability: dev` [here](https://github.com/bolt/bolt/blob/release/2.2/app/config/config.yml.dist#L390)

``` yaml
extensions:
    site: 'https://extensions.bolt.cm/'
    stability: dev
    enabled: true
```
